Pár hříček postavených na datasetu 2 291 817 nejvýznamnějších osobností historie, z nichž 13 795 má jako jednu z vlastí zaznamenanou Českou republiku či některý z předchozích státních útvarů. Pokud vás data zajímají víc, přečtěte si [původní článek v _Nature_](https://www.nature.com/articles/s41597-022-01369-4) a mou [stručnou kritiku metodologie](0%20Basic%20Data%20Exploration.ipynb).

In [3]:
import pandas as pd
whoiswho = pd.read_csv("cross-verified-database.csv", encoding='utf-8', encoding_errors='replace')

Dataset jde filtrovat podle státní příslušnosti. Háže to do jednoho pytle mnoho různých národností, ale to už tak státy dělávají.

In [4]:
ceskezeme = ["Old_(before_year_1993_AD)_Czech_Republic", "Czechoslovakia", "Czech_Republic", "Czechoslovakia,Czech_Republic"]

In [5]:
whoiswhocz = whoiswho[(whoiswho["area1_of_rattachment"].isin(ceskezeme)) | (whoiswho["area2_of_rattachment"].isin(ceskezeme)) | (whoiswho["list_areas_of_rattach"].str.contains('Cze')) | (whoiswho["list_areas_of_rattach"].str.contains('Kingdom_of_Bohemia'))].sort_values(by="sum_visib_ln_5criteria", ascending=False)
whoiswhocz.shape

(13795, 49)

## Největší Češi: Žid a Němec

In [6]:
nejvetsicech = whoiswhocz.reset_index()
nejvetsicech.index = nejvetsicech.index + 1
nejvetsicech[["name","level3_main_occ"]].head(50)

                              name level3_main_occ
1                      Franz_Kafka        novelist
2                      Thomas_Mann        novelist
3                   Antonín_Dvořák        composer
4              Martina_Navratilova          player
5                     Václav_Havel          writer
6                        Petr_Čech        football
7                  Bedřich_Smetana        composer
8                       Kurt_Gödel   mathematician
9                          Jan_Hus      theologian
10                   Milan_Kundera          writer
11                     Ivana_Trump          author
12              Madeleine_Albright      politician
13  Charles_IV,_Holy_Roman_Emperor       sovereign
14                    Miloš_Forman            film
15              John_Amos_Comenius     philosopher
16                    Pavel_Nedvěd        football
17                  Alphonse_Mucha          artist
18                      Ivan_Lendl          player
19                    Jaromír_Jágr          hockey
20                     Karel_Čapek          writer
21                   Petra_Kvitová          player
22          Tomáš_Garrigue_Masaryk     philosopher
23                    Emil_Zátopek        athletic
24                   Tomáš_Rosický        football
25                   Tomáš_Berdych          player
26                   Katie_Ledecky         swimmer
27                    Leoš_Janáček        composer
28                     Miloš_Zeman      politician
29                     Milan_Baroš        football
30                    Jana_Novotná          player
31                Alexander_Dubček      politician
32  Richard_von_Coudenhove-Kalergi      politician
33        Albrecht_von_Wallenstein        nobility
34                    Edvard_Beneš      politician
35                    Tom_Stoppard      playwright
36                  Jaroslav_Hašek          writer
37                      Adolf_Loos       architect
38                    Václav_Klaus      politician
39               Karolína_Plíšková          player
40                  Bohumil_Hrabal          writer
41                  Věra_Čáslavská         gymnast
42                      Jozef_Tiso      politician
43                Jaroslav_Seifert          writer
44      Joseph_Radetzky_von_Radetz         militar
45                      Karel_Gott          singer
46                Karolína_Kurková           model
47                    Silvia_Saint           actor
48                   Dominik_Hašek          hockey
49                 John_of_Nepomuk          priest
50                        Max_Brod          author

V _Hovorech s TGM_ byl Karel Čapek tím víc notable. Ještě tam s nimi mohla sedět Petra Kvitová!

Jiříka z Poděbrad hledali bychom marně, patrně nebude jediný, kdo chybí:

In [7]:
whoiswho[whoiswho["name"].str.contains("George_of_Poděbrady")][["list_areas_of_rattach"]].to_string()

"              list_areas_of_rattach\n283973  P:_'England'_can't_verifyB1"

Top 50 žen:

In [8]:
nejvetsicech[nejvetsicech["gender"] == "Female"][["name","level3_main_occ"]].head(50)

                             name  level3_main_occ
4             Martina_Navratilova           player
11                    Ivana_Trump           author
12             Madeleine_Albright       politician
21                  Petra_Kvitová           player
26                  Katie_Ledecky          swimmer
30                   Jana_Novotná           player
39              Karolína_Plíšková           player
41                 Věra_Čáslavská          gymnast
46               Karolína_Kurková            model
47                   Silvia_Saint            actor
53              Paulina_Porizkova            actor
56                 Lucie_Šafářová           player
70                   Lída_Baarová            actor
73   Sophie,_Duchess_of_Hohenberg         archduke
74                     Gerty_Cori       biochemist
79                  Eva_Herzigová          actress
81               Barbora_Strýcová           player
90             Gabriela_Koukalová          athlete
91                  Helena_Suková           player
95                Hana_Mandlíková           player
100                     Ewa_Farna           singer
103             Martina_Sáblíková            sport
106         Jarmila_Kratochvílová           runner
110             Libuše_Šafránková            actor
114               Milena_Jesenská       journalist
118               Markéta_Irglová          pianist
121               Anne_of_Bohemia            queen
122               Milada_Horáková       politician
131                 Nikita_Denise             film
135                 Petra_Němcová            model
137                 Ester_Ledecká        snowboard
148                Věra_Chytilová             film
150             Barbora_Špotáková  javelin_thrower
152                   Tarra_White            actor
155              Nicole_Vaidišová           player
157                  Dolly_Buster            actor
159                Lucie_Hradecká           player
167             Alice_Herz-Sommer            music
184            Kateřina_Siniaková           player
194                    Anny_Ondra            actor
196                     Jana_Cova            actor
207            Helena_Vondráčková            actor
211               Daniela_Peštová            model
212            Gabriela_Gunčíková           singer
213              Agnes_of_Bohemia              nun
216                 Marta_Jandová            music
218                    Lea_De_Mae          actress
219             Monica_Sweetheart            actor
222                         Toyen          painter
226            Ludmila_of_Bohemia             duke

Top 50 bez sportovců a sportovkyň (nic proti):

In [9]:
nejvetsicech[nejvetsicech["level2_main_occ"] != "Sports/Games"][["name","level3_main_occ"]].head(50)

                              name level3_main_occ
1                      Franz_Kafka        novelist
2                      Thomas_Mann        novelist
3                   Antonín_Dvořák        composer
5                     Václav_Havel          writer
7                  Bedřich_Smetana        composer
8                       Kurt_Gödel   mathematician
9                          Jan_Hus      theologian
10                   Milan_Kundera          writer
11                     Ivana_Trump          author
12              Madeleine_Albright      politician
13  Charles_IV,_Holy_Roman_Emperor       sovereign
14                    Miloš_Forman            film
15              John_Amos_Comenius     philosopher
17                  Alphonse_Mucha          artist
20                     Karel_Čapek          writer
22          Tomáš_Garrigue_Masaryk     philosopher
27                    Leoš_Janáček        composer
28                     Miloš_Zeman      politician
31                Alexander_Dubček      politician
32  Richard_von_Coudenhove-Kalergi      politician
33        Albrecht_von_Wallenstein        nobility
34                    Edvard_Beneš      politician
35                    Tom_Stoppard      playwright
36                  Jaroslav_Hašek          writer
37                      Adolf_Loos       architect
38                    Václav_Klaus      politician
40                  Bohumil_Hrabal          writer
42                      Jozef_Tiso      politician
43                Jaroslav_Seifert          writer
44      Joseph_Radetzky_von_Radetz         militar
45                      Karel_Gott          singer
46                Karolína_Kurková           model
47                    Silvia_Saint           actor
49                 John_of_Nepomuk          priest
50                        Max_Brod          author
52                    Ivan_Reitman            film
53               Paulina_Porizkova           actor
54                    Gustáv_Husák      politician
55                      Jan_Palach       political
57                Bohuslav_Martinů        composer
58                    Andrej_Babiš      politician
59   Wenceslaus_I,_Duke_of_Bohemia         monarch
60                Klement_Gottwald      politician
62                     Herbert_Lom           actor
64                       Jan_Žižka         militar
65           Ottokar_II_of_Bohemia         monarch
67              Adalbert_of_Prague          priest
68                 František_Kupka         painter
69                     Jan_Masaryk      politician
70                    Lída_Baarová           actor

Podle epoch:

In [10]:
pd.DataFrame(whoiswhocz.groupby("bigperiod_birth")["name"].first())

                                                    name
bigperiod_birth
2.Post-Classical History 501-1500AD              Jan_Hus
3.Early Modern Period 1501-1750AD     John_Amos_Comenius
4.Mid Modern Period 1751-1900AD              Franz_Kafka
5.Contemporary period 1901-2020AD    Martina_Navratilova
Missing                              Theodoric_of_Prague

In [11]:
pd.DataFrame(whoiswhocz[whoiswhocz["gender"] == "Female"].groupby("bigperiod_birth")["name"].first())

                                                             name
bigperiod_birth
2.Post-Classical History 501-1500AD               Anne_of_Bohemia
3.Early Modern Period 1501-1750AD      Eleonore_von_Schwarzenberg
4.Mid Modern Period 1751-1900AD      Sophie,_Duchess_of_Hohenberg
5.Contemporary period 1901-2020AD             Martina_Navratilova
Missing                                             Denise_Milani

Podle oborů:

In [12]:
pd.DataFrame(whoiswhocz.groupby("level2_main_occ")["name"].first())

                                                                name
level2_main_occ
Academia                                                  Kurt_Gödel
Administration/Law                                        Emil_Hácha
Corporate/Executive/Business (large)                      Tomáš_Baťa
Culture-core                                             Franz_Kafka
Culture-periphery                                         Adolf_Loos
Explorer/Inventor/Developer                            Aurel_Stodola
Family                                          Doubravka_of_Bohemia
Military                                  Joseph_Radetzky_von_Radetz
Missing                                      Eliska_Haskova_Coolidge
Nobility                              Charles_IV,_Holy_Roman_Emperor
Other                                                  Victor_Lustig
Politics                                          Madeleine_Albright
Religious                                            John_of_Nepomuk
Sports/Games                                     Martina_Navratilova
Worker/Business (small)                                 Karl_Koecher

In [13]:
pd.DataFrame(whoiswhocz[whoiswhocz["level2_main_occ"] == "Academia"].groupby("level3_main_occ")[["name","sum_visib_ln_5criteria"]].first()).sort_values(by="sum_visib_ln_5criteria", ascending=False)[["name"]].head(50)

                                               name
level3_main_occ
mathematician                            Kurt_Gödel
theologian                                  Jan_Hus
philosopher                      John_Amos_Comenius
biochemist                               Gerty_Cori
botanist                    Jan_Evangelista_Purkyně
chemist                          Jaroslav_Heyrovský
pharmacologist                          Rudolf_Vrba
psychiatrist                         Stanislav_Grof
historian                         František_Palacký
education                               Jiří_Drahoš
philologist                         Josef_Dobrovský
cosmonaut                            Vladimír_Remek
orientalist                          Bedřich_Hrozný
lexicographer                        Josef_Jungmann
physician                                Emil_Holub
political_scientist                    Karl_Deutsch
ecologist                    Elisabeth_Mann_Borgese
linguist                                René_Wellek
scholar                       Moritz_Steinschneider
geographer                              Vaclav_Smil
astronomer                             Tadeáš_Hájek
physicist                  František_Josef_Gerstner
art_historian                         Miroslav_Tyrš
economist                Tomáš_Sedláček_(economist)
neurologist                              Jan_Janský
anthropologist                       Lubor_Niederle
archaeologist                           Pavel_Pavel
nurse                               Vera_Salvequart
teacher                                Marek_Hilšer
surgeon                               Eduard_Albert
dean                           Božidara_Turzonovová
pedagogue                             Eduard_Štorch
paleontologist       Josef_Augusta_(paleontologist)
zoologist                           Antonin_Fritsch
palaeontologist                   Josephine_Kablick
ophthalmologist                     Georg_Prochaska
computer_scientist                      George_Klir
psychologist                        Zdeněk_Matějček
biologist                           Vratislav_Mazák
entomologist                Philipp_Maximilian_Opiz
aerospace                              Peter_Glaser
heraldist                           August_Sedláček
dermatologist                       Karl_Herxheimer
immunologist                              Jan_Klein
doctor                                   Leoš_Heger
professor                      Milena_Hübschmannová
museologist                 Zbyněk_Zbyslav_Stránský
academic                               Karel_Werner
egyptologist                          Jaromir_Málek
medievalist                         František_Graus

In [14]:
pd.DataFrame(whoiswhocz[whoiswhocz["gender"] == "Female"].groupby("level2_main_occ")["name"].first())

                                                              name
level2_main_occ
Academia                                                Gerty_Cori
Administration/Law                       Ludmila_Brožová-Polednová
Corporate/Executive/Business (large)                Šárka_Grossová
Culture-core                                           Ivana_Trump
Culture-periphery                                 Karolína_Kurková
Explorer/Inventor/Developer                        Renata_Chlumska
Family                                        Doubravka_of_Bohemia
Military                                            Marie_Ljalková
Missing                                    Eliska_Haskova_Coolidge
Nobility                              Sophie,_Duchess_of_Hohenberg
Other                                               Olga_Hepnarová
Politics                                        Madeleine_Albright
Religious                                         Agnes_of_Bohemia
Sports/Games                                   Martina_Navratilova
Worker/Business (small)                            Trude_Simonsohn

In [15]:
pd.DataFrame(whoiswhocz.groupby("level3_main_occ")["name"].first())

                                      name
level3_main_occ
abbot                       Andreas_Troyer
abt                        Arnošt_Vykoukal
academic                      Karel_Werner
activist                       Ivan_Bartoš
actor                         Silvia_Saint
...                                    ...
zahnarzt                     Artur_Pachner
zoolog                          Petr_Benda
zoologist                  Antonin_Fritsch
érudit                   Paulus_Paulirinus
évêque           John_Sobieslaw_of_Moravia

[519 rows x 1 columns]

In [16]:
pd.DataFrame(whoiswhocz[whoiswhocz["level2_main_occ"] == "Culture-core"].groupby("level3_main_occ")["name"].first())

                                       name
level3_main_occ
actor                          Silvia_Saint
actress                       Eva_Herzigová
animator                      Eduard_Hofman
art_critic                   Helena_Kontova
art_director     Karel_Černý_(art_director)
...                                     ...
tänzer                          Grete_Salus
violin                         Jan_Kalivoda
violist                        Milan_Škampa
vocalist                   Jarmila_Šuláková
writer                         Václav_Havel

[95 rows x 1 columns]

## Transgender lidé

In [17]:
whoiswhocz[(whoiswhocz["gender"] == "Other")][["name","birth","death"]].head(40)

                    name   birth   death
1216191    Zdeněk_Koubek  1913.0  1986.0
518470   Jeanette_Schmid  1924.0  2005.0

Oba osudy zajímavý: jak [Zdeňka Koubka](https://cs.wikipedia.org/wiki/Zden%C4%9Bk_Koubek_(1913%E2%80%931986)), tak „poslední pištkyně“ [Jeanette Baroness Lips von Lipstrill](https://cs.wikipedia.org/wiki/Jeanette_Baroness_Lips_von_Lipstrill).

## 30 pod 30

Inspirováno jednou učitelkou dějepisu na TikToku.

In [18]:
def thirty(year, area):
    whoiswho_filtered = whoiswho[whoiswho["area1_of_rattachment"].isin(area)]
    whoiswho_filtered = whoiswho_filtered[(whoiswho_filtered["birth"] > year - 30) & (whoiswho_filtered["birth"] < year - 17)]
    whoiswho_filtered = whoiswho_filtered.sort_values(by="sum_visib_ln_5criteria", ascending=False).head(30) 
    whoiswho_filtered["age"] = year - whoiswho_filtered["birth"]
    return whoiswho_filtered[["name", "age"]].set_index("name")

In [19]:
thirty(1848, ceskezeme)

                                               age
name
Karel_Havlíček_Borovský                       27.0
Josef_Mánes                                   28.0
Josef_Václav_Frič                             19.0
Benedikt_Roezl                                25.0
Jindřich_Fügner                               26.0
Bohuslav,_Count_Chotek_of_Chotkow_and_Wognin  19.0
Heinrich_von_Mattoni                          18.0
Vilém_Dušan_Lambl                             24.0
Václav_Treitz                                 29.0
Anton_Gindely                                 19.0
Josef_Leopold_Zvonař                          24.0
Pavel_Křížkovský                              28.0
Vojtěch_Šafařík                               19.0
Ignác_Šustala                                 26.0
Adolf_Kosárek                                 18.0
Quido_Mánes                                   20.0
Heinrich_Wankel                               27.0
Hermenegild_Jireček                           21.0
Vojtěch_Ignác_Ullmann                         26.0
Karel_Komzák_I                                25.0
Julius_Reisinger                              20.0
Soběslav_Pinkas                               21.0
Eduard_Grégr                                  21.0
František_Zdeněk_Skuherský                    18.0
Bedřich_Havránek                              27.0
Václav_František_Červený                      29.0
Karel_Svoboda_(artist)                        24.0
Josef_Pischna                                 22.0
Alois_von_Pražák                              28.0
Jaromír_von_Mundy                             26.0

In [20]:
thirty(1918, ceskezeme)

                     age
name
Karel_Čapek         28.0
Bohuslav_Martinů    28.0
Klement_Gottwald    22.0
Ludvík_Svoboda      23.0
Jaroslav_Heyrovský  28.0
Vítězslav_Nezval    18.0
Victor_Lustig       28.0
Richard_Réti        29.0
Vladislav_Vančura   27.0
Jiří_Wolker         18.0
Pavel_Haas          19.0
Vlasta_Burian       27.0
Karel_Teige         18.0
Zdeněk_Štěpánek     22.0
Hans_Krása          19.0
František_Tomášek   19.0
Emanuel_Moravec     25.0
Karel_Lamač         21.0
Jan_Mukařovský      27.0
Karel_Janoušek      25.0
Eduard_Čech         25.0
Konstantin_Biebl    20.0
Ferdinand_Peroutka  23.0
Jan_Zrzavý          28.0
Heliodor_Píka       21.0
Jindřich_Štyrský    19.0
Jaromír_Weinberger  22.0
Otto_Gutfreund      29.0
Josef_Skupa         26.0
František_Běhounek  20.0

In [21]:
thirty(1968, ceskezeme)

                                   age
name
Miloš_Zeman                       24.0
Václav_Klaus                      27.0
Věra_Čáslavská                    26.0
Karel_Gott                        29.0
Jan_Palach                        20.0
Antonín_Panenka                   20.0
Zdeněk_Zeman                      21.0
Jan_Hammer                        20.0
Jan_Kodeš                         22.0
Jiří_Drahoš                       19.0
Helena_Vondráčková                21.0
Vladimír_Remek                    20.0
Jiří_Bělohlávek                   22.0
Karel_Kryl                        24.0
Ivan_Hlinka                       18.0
Miroslav_Vitouš                   21.0
Marta_Kubišová                    26.0
Jiří_Kylián                       21.0
Tomáš_Halík                       20.0
Jana_Brejchová                    28.0
Marie,_Princess_of_Liechtenstein  28.0
Dominik_Duka                      25.0
Václav_Neckář                     25.0
Bolek_Polívka                     19.0
Josef_Abrhám                      29.0
Ivan_Mládek                       26.0
Karel_Brückner                    29.0
Helena_Fibingerová                19.0
Jozef_Adamec                      26.0
Ivo_Viktor                        26.0

## Imigrace a emigrace

In [22]:
nejvetsicech[(~nejvetsicech["area1_of_rattachment"].str.contains("Old")) & (~nejvetsicech["area1_of_rattachment"].str.contains("Cze"))].groupby("area1_of_rattachment")[["name","index"]].first().sort_values(by="index").head(50)

                                                      name    index
area1_of_rattachment
Slovakia                                      Andrej_Babiš    42866
South_Korea                                    Tomáš_Janda    93776
Romania                                     Ludovic_Mrazek   120547
Switzerland                                  Tatana_Sterba   150765
San_Marino                              Federico_Valentini   163247
Denmark                                 Franz_Xaver_Neruda   166938
Bosnia_and_Herzegovina                     Damir_Zlomislić   366845
Netherlands                                   Paul_Quasten   384646
Russia                                Vyacheslav_Karavayev   406670
Finland                                     Kristiina_Mäki   468670
Spain                                      Monika_Zgustová   585625
Belgium                                    Alizée_Poulicek   656292
Brazil                                       Vilém_Flusser   720902
Belarus                 Vladimir_Yemelyanov_(weightlifter)   738129
Austria-Hungary                            Milena_Jesenská   786194
US                                             Ivana_Trump   826195
Moldova                                   Anastasia_Dețiuc   856840
Bulgaria                                  Wassil_Boschinow   861663
Ukraine                                      Serhiy_Lyulka   870008
Lesotho                      Queen_'Masenate_Mohato_Seeiso   950737
Israel                                            Max_Brod   972839
United_Kingdom                                Tom_Stoppard  1021830
Hungary                                      László_Kubala  1024138
France                                        Anton_Reicha  1082127
Soviet_Union                                    Salo_Flohr  1110167
Greece                                       Loukas_Vyntra  1114469
Canada                                        Ivan_Reitman  1271494
Slovenia                                      Špela_Rogelj  1301746
Turkey                                    Ahmet_İlhan_Özek  1316521
Serbia_and_Montenegro                         Vladan_Binić  1321467
Austria                                         Kurt_Gödel  1326644
Norway                                    Milada_Blekastad  1358255
Holy_Roman_Empire                                  Jan_Hus  1365226
Germany                                   Otfried_Preußler  1373677
Armenia                                   Sergei_Movsesian  1390121
Kazakhstan                                  Jurij_Medveděv  1399365
Italy                               Angelo_Maria_Ripellino  1528633
Bangladesh                                    Oldrich_Svab  1561987
Australia                                   Dagmar_Bláhová  1569818
Madagascar                                  Erik_Rajohnson  1635895
Sweden                                       Joakim_Brodén  1709139
Vietnam                                       Filip_Nguyen  1734484
Venezuela                                     Carlos_Stohr  1765612
Poland                                       Piotr_Beczała  1853752
Mongolia                                    Jaroslav_Vacek  1860316
Serbia                                       Miloš_Karišik  2005698
Portugal                                František_Listopad  2038783
New_Zealand                                    Pavel_Tichý  2049697
India                                 S._N._Balagangadhara  2111003

In [23]:
nejvetsicech[(nejvetsicech["area1_of_rattachment"] == "US")][["name","level2_main_occ","level3_main_occ"]].head(10)

                      name level2_main_occ      level3_main_occ
11             Ivana_Trump    Culture-core               author
12      Madeleine_Albright        Politics           politician
14            Miloš_Forman    Culture-core                 film
26           Katie_Ledecky    Sports/Games              swimmer
53       Paulina_Porizkova    Culture-core                actor
131          Nikita_Denise    Culture-core                 film
399           Karl_Deutsch        Academia  political_scientist
409              Ivan_Kral    Culture-core               singer
458  Catherine_Breshkovsky        Politics           politician
588       Jessica_Fridrich        Academia        mathematician

In [24]:
nejvetsicech[(nejvetsicech["area1_of_rattachment"] == "United_Kingdom")][["name","level2_main_occ","level3_main_occ"]].head(10)

                        name level2_main_occ level3_main_occ
35              Tom_Stoppard    Culture-core      playwright
113              Karel_Reisz    Culture-core            film
180             Dominic_Raab        Politics      politician
257             Vera_Menchik    Sports/Games           chess
1946             Jana_Bellin    Sports/Games           chess
2667  Václav_Bolemír_Nebeský    Culture-core            poet
3071          Stephan_Körner        Academia     philosopher
3138            Zbyněk_Zeman        Academia       historian
3288            David_Preiss        Academia   mathematician
3673         James_McQuilkin    Sports/Games        football

In [25]:
nejvetsicech[(nejvetsicech["area1_of_rattachment"] == "Canada")][["name","level2_main_occ","level3_main_occ"]].head(10)

                 name level2_main_occ level3_main_occ
52       Ivan_Reitman    Culture-core            film
136       Stan_Mikita    Sports/Games          hockey
189   Vladimir_Kulich    Culture-core           actor
623       Vaclav_Smil        Academia      geographer
1306   Václav_Chvátal        Academia   mathematician
1465  Milena_Duchková    Sports/Games           diver
1901    Maria_Jelinek    Sports/Games          skater
2050   Milan_Kymlicka    Culture-core        composer
2609     Vlasta_Vrána    Culture-core           actor
2898   Oskar_Morawetz    Culture-core        composer

## Tipy na tvůrčí chvilku: osobnosti, které v roce 2019 neměly vlastní heslo na české nebo anglické Wikipedii

In [26]:
nejvetsicech[(~nejvetsicech["list_wikipedia_editions"].str.contains("cswiki")) & (nejvetsicech["level3_main_occ"] != "actor")][["name","bigperiod_birth","level2_main_occ","level3_main_occ"]].head(50)

,name,bigperiod_birth,level2_main_occ,level3_main_occ
180,Dominic_Raab,5.Contemporary period 1901-2020AD,Politics,politician
396,Josef_Blösche,5.Contemporary period 1901-2020AD,Politics,politician
486,Elisabeth_Mann_Borgese,5.Contemporary period 1901-2020AD,Academia,ecologist
525,Piotr_Beczała,5.Contemporary period 1901-2020AD,Culture-core,opera
588,Jessica_Fridrich,5.Contemporary period 1901-2020AD,Academia,mathematician
755,Blake_Schilb,5.Contemporary period 1901-2020AD,Sports/Games,basket
800,Max_Mannheimer,5.Contemporary period 1901-2020AD,Culture-core,writer
869,Ulas_Samchuk,5.Contemporary period 1901-2020AD,Culture-periphery,journalist
879,Joe_Nemechek,5.Contemporary period 1901-2020AD,Sports/Games,nascar
893,Kayla_Day,5.Contemporary period 1901-2020AD,Sports/Games,player
937,Otto_Kerner_Jr.,5.Contemporary period 1901-2020AD,Politics,politician
944,Logan_Ondrusek,5.Contemporary period 1901-2020AD,Sports/Games,baseball
948,Kevin_Ware,5.Contemporary period 1901-2020AD,Sports/Games,basket
1045,Charles_Fried,5.Contemporary period 1901-2020AD,Administration/Law,lawyer
1080,Bronisław_Czech,5.Contemporary period 1901-2020AD,Sports/Games,skier
1156,Heinz_Tiessen,4.Mid Modern Period 1751-1900AD,Culture-core,composer
1171,Nicole_Bobek,5.Contemporary period 1901-2020AD,Sports/Games,skater
1175,Werner_von_Gilsa,4.Mid Modern Period 1751-1900AD,Military,militar
1224,Ottla_Kafka,4.Mid Modern Period 1751-1900AD,Family,sister
1261,Anna_Kalinskaya,5.Contemporary period 1901-2020AD,Sports/Games,player
1320,Vera_Salvequart,5.Contemporary period 1901-2020AD,Academia,nurse
1329,Hannes_Hegen,5.Contemporary period 1901-2020AD,Culture-core,artist
1388,Kenny_George,5.Contemporary period 1901-2020AD,Sports/Games,basket
1407,Tatana_Sterba,5.Contemporary period 1901-2020AD,Culture-core,dance
1418,Yozhef_Betsa,5.Contemporary period 1901-2020AD,Sports/Games,football
1425,Walter_von_Molo,4.Mid Modern Period 1751-1900AD,Culture-core,writer
1439,Alizée_Poulicek,5.Contemporary period 1901-2020AD,Culture-periphery,model
1464,Dmytro_Doroshenko,4.Mid Modern Period 1751-1900AD,Politics,politician
1472,Maria_Müller,4.Mid Modern Period 1751-1900AD,Culture-core,singer
1475,Kia_Vaughn,5.Contemporary period 1901-2020AD,Sports/Games,basket
1488,Elia_Cmíral,5.Contemporary period 1901-2020AD,Culture-core,composer
1516,Vasik_Rajlich,5.Contemporary period 1901-2020AD,Sports/Games,chess
1558,Szymon_Czechowicz,3.Early Modern Period 1501-1750AD,Culture-core,painter
1605,Richard_Petruška,5.Contemporary period 1901-2020AD,Sports/Games,basket
1677,Špela_Rogelj,5.Contemporary period 1901-2020AD,Sports/Games,ski
1754,Michel_Kratochvil,5.Contemporary period 1901-2020AD,Sports/Games,player
1768,Otto_Dov_Kulka,5.Contemporary period 1901-2020AD,Academia,historian
1776,Danielle_Robinson,5.Contemporary period 1901-2020AD,Sports/Games,basket
1794,Roman_Hruska,5.Contemporary period 1901-2020AD,Politics,politician
1815,Ivan_Franěk,5.Contemporary period 1901-2020AD,Culture-core,cinema
1901,Maria_Jelinek,5.Contemporary period 1901-2020AD,Sports/Games,skater
1917,Paul_Kraus_(Arabist),5.Contemporary period 1901-2020AD,Academia,orientalist
1929,Frank_Popper,5.Contemporary period 1901-2020AD,Academia,art_historian
1931,Vasyl_Kasiyan,4.Mid Modern Period 1751-1900AD,Culture-core,artist
1997,Leopoldine_von_Sternberg,3.Early Modern Period 1501-1750AD,Nobility,princess
2008,Hellmut_Diwald,5.Contemporary period 1901-2020AD,Academia,historian
2027,Lucie_Voňková,5.Contemporary period 1901-2020AD,Sports/Games,football
2032,Charles_Vanik,5.Contemporary period 1901-2020AD,Politics,politician
2070,George_Klir,5.Contemporary period 1901-2020AD,Academia,computer_scientist
2106,Federico_Valentini,5.Contemporary period 1901-2020AD,Sports/Games,football

In [27]:
nejvetsicech[(~nejvetsicech["list_wikipedia_editions"].str.contains("enwiki")) & (nejvetsicech["level3_main_occ"] != "actor")][["name","bigperiod_birth","level2_main_occ","level3_main_occ"]].head(50)

,name,bigperiod_birth,level2_main_occ,level3_main_occ
243,Veronika_Zemanová,5.Contemporary period 1901-2020AD,Culture-core,singer
461,Little_Caprice,5.Contemporary period 1901-2020AD,Culture-periphery,model
811,Denise_Milani,Missing,Culture-periphery,model
870,Jiří_Hanzelka_(explorateur),5.Contemporary period 1901-2020AD,Culture-core,writer
1015,Angelo_Maria_Ripellino,5.Contemporary period 1901-2020AD,Culture-core,poet
1020,Jiří_Růžek,5.Contemporary period 1901-2020AD,Culture-core,photographer
1082,Adolf_Hoffmeister,5.Contemporary period 1901-2020AD,Culture-core,writer
1449,Josef_Toufar,5.Contemporary period 1901-2020AD,Religious,priest
1785,Václav_Malý,5.Contemporary period 1901-2020AD,Religious,priest
1881,Eduard_Goldstücker,5.Contemporary period 1901-2020AD,Academia,education
1890,Vítězslav_Jandák,5.Contemporary period 1901-2020AD,Politics,politician
1892,Miloš_Říha,5.Contemporary period 1901-2020AD,Sports/Games,hockey
1897,Petr_Uhl,5.Contemporary period 1901-2020AD,Politics,politician
1909,Milan_Lasica,5.Contemporary period 1901-2020AD,Culture-core,comedian
1942,Filip_Bandžak,5.Contemporary period 1901-2020AD,Culture-core,opera
1943,Miloslav_Stingl,5.Contemporary period 1901-2020AD,Culture-core,writer
1948,Franz_Martin_Pelzel,3.Early Modern Period 1501-1750AD,Academia,historian
2015,Peter_Jilemnický,5.Contemporary period 1901-2020AD,Culture-core,writer
2033,Josef_Schulz,4.Mid Modern Period 1751-1900AD,Culture-periphery,architect
2048,Gelasius_Dobner,3.Early Modern Period 1501-1750AD,Academia,historian
2081,František_Xaver_Šalda,4.Mid Modern Period 1751-1900AD,Culture-core,literary
2146,Petr_Janda_(Musiker),5.Contemporary period 1901-2020AD,Culture-core,composer
2161,Pavel_Brázda,5.Contemporary period 1901-2020AD,Culture-core,painter
2178,Gustav_Janouch,5.Contemporary period 1901-2020AD,Culture-core,author
2238,Stepan_Rudnyzkyj,4.Mid Modern Period 1751-1900AD,Academia,geographer
2248,Markéta_Bělonohá,5.Contemporary period 1901-2020AD,Culture-periphery,model
2271,Heinrich_von_Mattoni,4.Mid Modern Period 1751-1900AD,Corporate/Executive/Business (large),entrepreneur
2291,František_Kožík,5.Contemporary period 1901-2020AD,Culture-core,drama
2381,Jan_Faktor,5.Contemporary period 1901-2020AD,Culture-core,writer
2382,Eva_Aichmajerová,5.Contemporary period 1901-2020AD,Culture-periphery,model
2424,Adolf_Pascher,4.Mid Modern Period 1751-1900AD,Academia,botanist
2462,Pavlína_Filipovská,5.Contemporary period 1901-2020AD,Culture-core,writer
2488,Vaclav_Radimsky,4.Mid Modern Period 1751-1900AD,Culture-core,painter
2490,Susana_Spears,5.Contemporary period 1901-2020AD,Culture-periphery,youtuber
2506,Josef_Slavík,4.Mid Modern Period 1751-1900AD,Culture-core,composer
2511,Karol_Duchoň,5.Contemporary period 1901-2020AD,Culture-core,singer
2516,Rajko_Doleček,5.Contemporary period 1901-2020AD,Academia,physician
2607,Michel_Fingesten,4.Mid Modern Period 1751-1900AD,Culture-core,painter
2696,František_Václav_Lobkowicz,5.Contemporary period 1901-2020AD,Religious,priest
2702,Nikola_Šuhaj,4.Mid Modern Period 1751-1900AD,Other,thief
2707,Karel_Štědrý,5.Contemporary period 1901-2020AD,Culture-core,singer
2721,Karel_Černoch,5.Contemporary period 1901-2020AD,Culture-core,singer
2723,Vladimír_Krajina,5.Contemporary period 1901-2020AD,Academia,botanist
2729,Giovanni_Battista_Alliprandi,3.Early Modern Period 1501-1750AD,Culture-periphery,architect
2758,Karel_Svolinský,4.Mid Modern Period 1751-1900AD,Culture-core,painter
2775,Ota_Hofman,5.Contemporary period 1901-2020AD,Culture-core,writer
2791,Václav_Erben,5.Contemporary period 1901-2020AD,Culture-core,screenwriter
2801,Ignaz_Franz_Platzer,3.Early Modern Period 1501-1750AD,Culture-core,sculptor
2819,Ivana_Mrázová,5.Contemporary period 1901-2020AD,Culture-periphery,model
2827,Petr_Kotvald,5.Contemporary period 1901-2020AD,Culture-core,singer